// <auto-generated />
using AnatoliaSmmPanel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnatoliaSmmPanel.Data.Migrations.Home
{
    [DbContext(typeof(HomeContext))]
    [Migration("20260507215610_AddMenu")]
    partial class AddMenu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnatoliaSmmPanel.Areas.Admin.Models.AdminMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdminOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NavigationTargetId")
                        .HasColumnType("int");

                    b.Property<bool>("OpenInNewTab")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RequiredRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NavigationTargetId");

                    b.ToTable("AdminMenus");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Areas.Admin.Models.AdminMenuPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminMenuId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminMenuId");

                    b.ToTable("AdminMenuPermissions");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Areas.Admin.Models.AdminSubMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminMenuId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdminOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NavigationTargetId")
                        .HasColumnType("int");

                    b.Property<bool>("OpenInNewTab")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminMenuId");

                    b.HasIndex("NavigationTargetId");

                    b.ToTable("AdminSubMenus");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Areas.Admin.Models.AdminSubMenuPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminSubMenuId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminSubMenuId");

                    b.ToTable("AdminSubMenuPermissions");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Models.AuthMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdminOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NavigationTargetId")
                        .HasColumnType("int");

                    b.Property<bool>("OpenInNewTab")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NavigationTargetId");

                    b.ToTable("AuthMenus");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Models.AuthMenuPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthMenuId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthMenuId");

                    b.ToTable("AuthMenuPermissions");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdminOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NavigationTargetId")
                        .HasColumnType("int");

                    b.Property<bool>("OpenInNewTab")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NavigationTargetId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Models.MenuPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuPermissions");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Models.NavigationTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenuConnect")
                        .HasColumnType("int");

                    b.Property<string>("Page")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartialView")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NavigationTargets");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Areas.Admin.Models.AdminMenu", b =>
                {
                    b.HasOne("AnatoliaSmmPanel.Models.NavigationTarget", "NavigationTarget")
                        .WithMany()
                        .HasForeignKey("NavigationTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NavigationTarget");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Areas.Admin.Models.AdminMenuPermission", b =>
                {
                    b.HasOne("AnatoliaSmmPanel.Areas.Admin.Models.AdminMenu", "AdminMenu")
                        .WithMany("AdminMenuPermissions")
                        .HasForeignKey("AdminMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminMenu");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Areas.Admin.Models.AdminSubMenu", b =>
                {
                    b.HasOne("AnatoliaSmmPanel.Areas.Admin.Models.AdminMenu", "AdminMenu")
                        .WithMany()
                        .HasForeignKey("AdminMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnatoliaSmmPanel.Models.NavigationTarget", "NavigationTarget")
                        .WithMany()
                        .HasForeignKey("NavigationTargetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AdminMenu");

                    b.Navigation("NavigationTarget");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Areas.Admin.Models.AdminSubMenuPermission", b =>
                {
                    b.HasOne("AnatoliaSmmPanel.Areas.Admin.Models.AdminSubMenu", "AdminSubMenu")
                        .WithMany("AdminSubMenuPermissions")
                        .HasForeignKey("AdminSubMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminSubMenu");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Models.AuthMenu", b =>
                {
                    b.HasOne("AnatoliaSmmPanel.Models.NavigationTarget", "NavigationTarget")
                        .WithMany()
                        .HasForeignKey("NavigationTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NavigationTarget");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Models.AuthMenuPermission", b =>
                {
                    b.HasOne("AnatoliaSmmPanel.Models.AuthMenu", "AuthMenu")
                        .WithMany("authMenuPermissions")
                        .HasForeignKey("AuthMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthMenu");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Models.Menu", b =>
                {
                    b.HasOne("AnatoliaSmmPanel.Models.NavigationTarget", "NavigationTarget")
                        .WithMany()
                        .HasForeignKey("NavigationTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NavigationTarget");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Models.MenuPermission", b =>
                {
                    b.HasOne("AnatoliaSmmPanel.Models.Menu", "Menu")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Areas.Admin.Models.AdminMenu", b =>
                {
                    b.Navigation("AdminMenuPermissions");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Areas.Admin.Models.AdminSubMenu", b =>
                {
                    b.Navigation("AdminSubMenuPermissions");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Models.AuthMenu", b =>
                {
                    b.Navigation("authMenuPermissions");
                });

            modelBuilder.Entity("AnatoliaSmmPanel.Models.Menu", b =>
                {
                    b.Navigation("MenuPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
